# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-26 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20161125_2000'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tagline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
            ],
        ),
    ]
