# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-26 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_tagline'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='abstract',
            field=models.TextField(default='abstract here'),
            preserve_default=False,
        ),
    ]
