# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-18 15:25
from __future__ import unicode_literals

from django.db import migrations
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_abstract'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content',
            field=froala_editor.fields.FroalaField(default=''),
            preserve_default=False,
        ),
    ]
