# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-19 22:37
from __future__ import unicode_literals

from django.db import migrations, models
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('content', froala_editor.fields.FroalaField()),
            ],
        ),
    ]
