# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-20 02:30
from __future__ import unicode_literals

from django.db import migrations
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20170119_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='abstract',
            field=froala_editor.fields.FroalaField(),
        ),
    ]
